### ISSUE TITLE
Error loading starrevoke

### ISSUE THREAD

**Issue by Azazel020** [yusufferdogan/REVOKE-STARKNET#6]
I can connect with starrevoke but after connecting the ArgentX wallet the site keeps loading end ends up with an error.

![2023-11-09 17_17_27-StarkRevoke - Starknet Approve Revoker](https://github.com/yusufferdogan/STARKREVOKE/assets/44430967/814d7605-e66d-4e72-87ed-3c667ceca8ec)

**Comment by yusufferdogan** [comment]
It is solved can you check?

**Comment by Azazel020** [comment]
Just checked but still getting an error. See attachments

![2023-11-12 08_53_33-StarkRevoke - Starknet Approve Revoker](https://github.com/yusufferdogan/STARKREVOKE/assets/44430967/25a44733-6038-4eda-a383-a4538e2d5a68)
![2023-11-12 08_54_48-StarkRevoke - Starknet Approve Revoker](https://github.com/yusufferdogan/STARKREVOKE/assets/44430967/ac581b69-eb4d-47a5-ae92-2205f378158e)

**Comment by yusufferdogan** [comment]
![image](https://github.com/yusufferdogan/STARKREVOKE/assets/45846424/83d0ac8b-9d16-4b87-962a-bd49c987c2e2)
it's working on chrome

**Comment by Azazel020** [comment]
Not for me, also on Chrome connected with an ArgentX wallet.

Chrome is up-to-date
Versie 119.0.6045.124 (Officiële build) (64-bits)
